version: "3"

services:
  app:
    build: .
    command: bin/rails s
    volumes:
      - gem:/usr/local/bundle
      - .:/bblog
    ports:
      - 3000:3000

  db:
    image: postgres:10.1
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  gem:
