version: "3"

services:
  app:
    build: .
    command: bin/rails s
    volumes:
      - gem:/usr/local/bundle
      - .:/bblog
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres@db

  test:
    build: .
    command: bin/rails spec
    volumes:
      - gem:/usr/local/bundle
      - .:/bblog
    environment:
      - DATABASE_URL=postgres://postgres@db
      - RAILS_ENV=test

  db:
    image: postgres:10.1
    volumes:
      - db-data:/var/lib/postgresql/data

  chrome:
    image: selenium/standalone-chrome-debug:3.8.1
    ports:
      - "5900:5900"

volumes:
  db-data:
  gem:
